<html>
<head>
	<title>OnApp PHP wrapper documentation</title>
			<link rel="stylesheet" href="{$subdir}media/stylesheet.css" />
			<meta http-equiv='Content-Type' content='text/html; charset=iso-8859-1'/>
</head>
<body>
    <div class="page-body">
        <h2 class="blank-header">OnApp PHP wrapper documentation</h2>
        <br />
<p>The OnApp cloud engine is a unique software tool for hosting providers. Using commodity hardware, it lets hosts deploy clouds and manage cloud resources, failover, users and billing.</p>
<p>The OnApp API wrapper allows you to automate OnApp virtual machine operations, and run programs or manipulate files within third party applications. It's a high-level API that's easy to use, and practical for both script writers and application programmers.</p>
<p>This document is a detailed API reference resource that includes information about classes, functions, files, and other wrapper elements. All function calls respond to xml requests - response to Json requests is a planned feature. It is organized into the following chapters:</p>
<p><b>Classes:</b> sections that describe classes, each of which contains a list of methods and variables that can operate on that class. Each section contains information about the purpose of a class. The Methods subsections contain the usual reference information such as syntax, parameters, and return codes.</p>
<p><b>Files:</b> contains a list of the OnApp API header files. You can look at individual files in this chapter and see the classes that they contain.</p>

        This documentation was generated by <a href="{$phpdocwebsite}">phpDocumentor v{$phpdocversion}</a><br />
    </div>
</body>
</html>
